### ISSUE TITLE
Figure out where to store EVENT_TARGET secrets in infrastructure

### ISSUE THREAD

**Issue by gobengo** [elastic-ipfs/event-delivery-lambda#6]
Motivation
* event-delivery lambda delivers events to another service configured via env var `EVENT_TARGET`
* in practice in staging, we'll want `EVENT_TARGET=https://{user}:{password}@indexer-metrics-collector-staging.protocol-labs.workers.dev/`
  * without this, the [metrics-collector](https://github.com/elastic-ipfs/metrics-collector) will disallow the POST /events request
* `{password}` is a secret, so probably this whole env var can be considered a secret.

Problem
* How/where do I write the EVENT_TARGET secret such that event-delivery-lambda staging environment has that secret as the value for EVENT_TARGET environment variable?

**Comment by gobengo** [comment]
@francardoso93 said he would talk to others about the best way to do this the right way, probably https://docs.aws.amazon.com/secretsmanager/

**Comment by gobengo** [comment]
@francardoso93 It would be really nice to be able to manage this as close to the individual microservices as possible, and not necessarily in the 'infrastructure' codebase. e.g. since event-delivery-lambda repos github actions are what deploys to staging/production, it would be nice to be able to use the github actions 'environments' secrets to configure those environments.

What if the [elastic-ipfs/shared-workflows/.../lambda-shared-deploy](https://github.com/elastic-ipfs/shared-workflows/blob/main/.github/workflows/lambda-shared-deploy.yaml#L49) automatically managed an AWS Secret Manager instance?

I could configure it in the github action by providing a newline-delimited list of env variables that should be written into AWS Secret Manager as `lambda_secret_envs`

```
  deploy-to-staging:
    uses: elastic-ipfs/shared-workflows/.github/workflows/lambda-shared-deploy.yaml@main
    permissions:
      id-token: write
    needs: build-staging
    with:
      deploy_to_environment: staging
      lambda: staging-ep-indexer
      docker_image_version: ${{ needs.build-staging.outputs.build_date }}
      lambda_secret_envs: |
        EVENT_TARGET
        OTHER_SECRET
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_STAGING }}
```
